### ISSUE TITLE
Contributing to Emacs?

### ISSUE THREAD

**Issue by nemethf** [slotThe/vc-use-package#10]
`vc-use-package` seems very useful.  Have you thought about contributing it to upstream Emacs where both `package-vc-install` and `use-package` live?

**Comment by slotThe** [comment]
> `vc-use-package` seems very useful.

Thanks!

> Have you thought about contributing it to upstream Emacs where both `package-vc-install` and `use-package` live?

I have, yes.  I [prepared a patch](https://lists.gnu.org/archive/html/bug-gnu-emacs/2022-12/msg02500.html) a while ago, but it seems like no one had a chance to look at it so far.  I suppose we have to be patient :)

**Comment by nemethf** [comment]
> I suppose we have to be patient :)

I admire your attitude.

**Comment by elken** [comment]
> but it seems like no one had a chance to look at it so far.

Feel free to bump it, it's a very busy time atm. If you're quick it might just squeeze into 29, but I doubt it

**Comment by slotThe** [comment]
> > but it seems like no one had a chance to look at it so far.
> 
> Feel free to bump it, it's a very busy time atm. If you're quick it might just squeeze into 29, but I doubt it

By now, it has gathered some comments, and is—I think—almost ready to be merged (see e.g. [here](https://lists.gnu.org/archive/cgi-bin/namazu.cgi?query=Add+%3Avc+keyword+to+use-package&submit=Search%21&idxname=bug-gnu-emacs&max=100&result=normal&sort=date%3Alate)). I think Emacs 29 will only receive bugfixes at this point, not new features, so people will probably have to wait until 30 to use it in a released version

**Comment by slotThe** [comment]
[:)](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=2ce279680bf9c1964e98e2aa48a03d6675c386fe&context=3&ignorews=0&dt=0)
