### ISSUE TITLE
Feature request: :files

### ISSUE THREAD

**Issue by mikezackles** [slotThe/vc-use-package#11]
Hi! Thanks for putting this together!

I couldn't figure out how to install [dirvish](https://github.com/alexluigit/dirvish) from git using this package.

I noticed that the melpa recipe looks like this:
```
(dirvish :fetcher github :repo "alexluigit/dirvish"
         :files (:defaults "extensions/*.el" ))
```

`vc-use-package` doesn't appear to support `:files`, so I had to resort to using `straight.el`, which does do this out of the box. Perhaps  `:files` support could be a worthwhile addition to provide compatibility with more packages?

Thanks again!

**Comment by slotThe** [comment]
Hi,

you should be able to do this by directly using the `package-vc.el` interface:

``` emacs-lisp
(use-package dirvish
  :vc (dirvish :url "https://github.com/alexluigit/dirvish"
               :lisp-dir "extensions/"))
```

Bringing any file within the extension directory into scope should then work as normal with e.g. `(require 'dirvish-ls)`.

**Comment by mikezackles** [comment]
Oh, excellent, thank you! I'll give this a shot.

**Comment by mikezackles** [comment]
That did the trick -- thanks again!
