### ISSUE TITLE
Exclude files

### ISSUE THREAD

**Issue by danielfleischer** [slotThe/vc-use-package#12]
Similar to #11, keyword `:files` can help exclude some elisp files; some packages have extra extensions (org-ql + helm support) which can be excluded. Is there a way to support that?

**Comment by slotThe** [comment]
> Is there a way to support that?

I don't believe so. Fundamentally, we are still constrained to the API that `package-vc.el` supports, and—at least currently—it does not support excluding files. Perhaps this could be a feature request to Emacs instead? I don't think this would be particularly hard to implement (famous last words, I know, but still).

(Personally, I also think it's better for this to be implemented at the package level; split off `orq-ql-helm.el` into an extra package, instead of having to awkwardly ignore single elisp files)

**Comment by danielfleischer** [comment]
> (Personally, I also think it's better for this to be implemented at the package level; split off `orq-ql-helm.el` into an extra package, instead of having to awkwardly ignore single elisp files)

Exactly the usecase I had in mind! 

I started a discussion on the [mailing list](https://lists.gnu.org/archive/html/emacs-devel/2023-06/msg00244.html). It appears there's an inherent technical and philosophical difference between ELPA packages and MELPA packages such that recipes can't be compatible and file-ignoring is not necessary when you follow ELPA packaging guideline. I could be wrong though. Either way, `package-vc` appears to not fill my needs right now. Maybe that'll change in the future.

**Comment by alphapapa** [comment]
> (Personally, I also think it's better for this to be implemented at the package level; split off `orq-ql-helm.el` into an extra package, instead of having to awkwardly ignore single elisp files)

`helm-org-ql` is a separate package.  Its source code file happens to live in the same repository as `org-ql`.  For small, ancillary packages like `helm-org-ql`, it's often easier for the author to keep it together with the "parent" package.

> ELPA packages and MELPA packages such that recipes can't be compatible and file-ignoring is not necessary when you follow ELPA packaging guideline.

It appears that at least 65 ELPA packages include `:ignored-files` in their recipes (see the `elpa-packages` file).

So it would seem that this is a reality that `package-vc` needs to handle.

**Comment by slotThe** [comment]
Implemented as of https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=68318dfd1652151f7d08f7682303499494a0c427

Thanks everyone for bringing this along!
