### ISSUE TITLE
how to update all vc-controlled packages 

### ISSUE THREAD

**Issue by emacsomancer** [slotThe/vc-use-package#14]
is there a way (automatic or manual) to update all packages controlled by `vc-use-package`?

**Comment by slotThe** [comment]
`package-upgrade-all` upgrades all of your packages, which includes those installed by `package-vc`. Alternatively, there's also `package-vc-upgrade-all`, which *only* touches vc packages

**Comment by slotThe** [comment]
@emacsomancer I will close this for now, as I think the above commands resolve your issue. Feel free to chime back in if you have any further questions :)

**Comment by emacsomancer** [comment]
Sometimes it seems to end with errors like "package not under version control" or "missing package description". Mainly restarting Emacs seems to resolve these issues.

**Comment by slotThe** [comment]
Huh, interesting; I've never encountered these errors before. Though they seem like issues with `package-vc` itself (`vc-use-package` has no control over anything that happens *after* installing a package), so if this happens again I would encourage you to open an Emacs bug
