### ISSUE TITLE
Please provide an example.

### ISSUE THREAD

**Issue by goberlan** [slotThe/vc-use-package#15]
https://github.com/slotThe/vc-use-package?tab=readme-ov-file#in-combination-with-use-package-always-ensure

Hello, I am excited to use this package; however, I don't understand the section I linked above.  Can you please provide an elisp/config code example of what you mean in this section? Explaining how to use something is never as effective as just showing how to use it...  

Am I suppose to put always-ensure above every `use-package` statement? Likely no.. So, am i suppose to put it above this?
```
(unless (package-installed-p 'vc-use-package)
  (package-vc-install "https://github.com/slotThe/vc-use-package"))
```
Or, do I put it after, etc. Your description is not clear.

**Comment by slotThe** [comment]
If you don't set If you don't set `use-package-always-ensure` then you don't need to worry about this. Otherwise, you need to make sure that `vc-use-package` is loaded after setting the variable.

``` emacs-lisp
(setopt use-package-always-ensure)
(require 'vc-use-package)
```
