### ISSUE TITLE
Empty checkout for vc-use-package

### ISSUE THREAD

**Issue by zcjava** [slotThe/vc-use-package#19]
use 
(unless (package-installed-p 'vc-use-package)
  (package-vc-install "https://github.com/slotThe/vc-use-package"))
(require 'vc-use-package)

can't download vc-use-package , error Empty checkout for vc-use-package

**Comment by zcjava** [comment]
emacs version 29.4

**Comment by slotThe** [comment]
Something failed when cloning the repository. At that point, vc-use-package is not even engaged yet, so this seems like more of a package-vc.el issue; I've found its errors to not be super descriptive. Perhaps stepping through the cloning functions with edebug or something similar will yield results?
