### ISSUE TITLE
Cannot install package's revision

### ISSUE THREAD

**Issue by alternateved** [slotThe/vc-use-package#2]
Hello!

When trying to use `:rev` keyword with a string I get an error like:
```
 ■  Error (use-package): Failed to parse package modus-themes: Wrong type argument: number-or-marker-p, "version-4"
```

Example snippet:
```lisp
(use-package modus-themes
  :vc (:fetcher "sourcehut" :repo "protesilaos/modus-themes" :rev "version-4"))
```

I've found that switching ([line 86 of vc-use-package.el](https://github.com/slotThe/vc-use-package/blob/master/vc-use-package.el#L86)):
```lisp
(:rev (if (= val :last-release) val (mk-string val)))
```
With:
```lisp
(:rev (if (eq val :last-release) val (mk-string val)))
```
Enables it to work properly, though I have no idea exactly why. 

Also I am not sure how `:last-release` could work here as `:fetcher` `:repo` `:rev` `:backend` are the only allowed keywords. I guess this could fix it, though I am not sure if it is properly designed:
```lisp
(defvar vc-use-package-keywords
  '(:fetcher :repo :rev :backend :last-release)
  "All arguments that `package-vc-install' supports.")
```

Best regards,
alternateved

**Comment by slotThe** [comment]
> I've found that switching ([line 86 of vc-use-package.el](https://github.com/slotThe/vc-use-package/blob/master/vc-use-package.el#L86)):
> 
> ```lisp
> (:rev (if (= val :last-release) val (mk-string val)))
> ```
> 
> With:
> 
> ```lisp
> (:rev (if (eq val :last-release) val (mk-string val)))
> ```
> 
> Enables it to work properly, though I have no idea exactly why.

Ah, the wonders of having 100 ways to compare things because we are missing ad-hoc polymorphism :).  I'll fix this, thanks!

> Also I am not sure how `:last-release` could work here as `:fetcher` `:repo` `:rev` `:backend` are the only allowed keywords.

The `:last-release` keyword is actually an _argument_ to the `:rev` keyword, not one on its own.  You can use it like 

```lisp
(use-package blah
  :vc (:fetcher "hi" 
       :repo "hi" 
       :rev :last-release))
```

EDIT: This should probably be documented better, though (I just copied this from `package-vc-install`, but it may still be worth mentioning this explicitly)

**Comment by alternateved** [comment]
The problem is that it is treated as one on its own like here:
```lisp
(use-package modus-themes
  :vc (:fetcher "sourcehut" :repo "protesilaos/modus-themes" :rev :last-release))
```
Greets me with error:
```
 ■  Error (use-package): Failed to parse package modus-themes: use-package: :vc declaration contains unknown keywords: (:last-release).  Known keywords are: (:fetcher :repo :rev :backend)
 ```

**Comment by slotThe** [comment]
Oh, right, sorry; I'm too used to Clojure's amazing first class map support that I expect plists to behave nicely all the time as well :)

Could you try 043cf1131a5cbb10197b92f3670dff2a0009ceb8 ?

**Comment by alternateved** [comment]
Yes, that works splendidly! Thanks.
